import { createDefaultModule, DefaultModuleContext, inject, LangiumServices, Module, PartialLangiumServices } from 'langium';
import { EasyLanguageArduinoGeneratedModule } from './generated/module';
import { EasyLanguageArduinoValidationRegistry, EasyLanguageArduinoValidator } from './easy-language-arduino-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type EasyLanguageArduinoAddedServices = {
    validation: {
        EasyLanguageArduinoValidator: EasyLanguageArduinoValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type EasyLanguageArduinoServices = LangiumServices & EasyLanguageArduinoAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const EasyLanguageArduinoModule: Module<EasyLanguageArduinoServices, PartialLangiumServices & EasyLanguageArduinoAddedServices> = {
    validation: {
        ValidationRegistry: (injector) => new EasyLanguageArduinoValidationRegistry(injector),
        EasyLanguageArduinoValidator: () => new EasyLanguageArduinoValidator()
    }
};

/**
 * Inject the full set of language services by merging three modules:
 *  - Langium default services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 */
export function createEasyLanguageArduinoServices(context?: DefaultModuleContext): EasyLanguageArduinoServices {
    return inject(
        createDefaultModule(context),
        EasyLanguageArduinoGeneratedModule,
        EasyLanguageArduinoModule
    );
}
